=== whitespace-v/xml/xsd/demo-2.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="root">
    <xs:complexType>
      <xs:sequence>
        <!-- строки -->
        <xs:element name="str" type="xs:string"/>
        <xs:element name="lang" type="xs:language"/>
        <xs:element name="name" type="xs:Name"/>
        <xs:element name="ncname" type="xs:NCName"/>
        <!-- числа -->
        <xs:element name="byte" type="xs:byte"/>
        <xs:element name="positive" type="xs:positiveInteger"/>
        <xs:element name="positive-or-zero" type="xs:nonNegativeInteger"/>
        <!-- дата и время -->
        <xs:element name="now" type="xs:dateTime"/>
        <xs:element name="birthday" type="xs:date"/>
        <xs:element name="period" type="xs:duration"/>
        <!-- другое -->
        <xs:element name="bool" type="xs:boolean"/>
        <xs:element name="hex" type="xs:hexBinary"/>
        <xs:element name="url" type="xs:anyURI"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== whitespace-v/xml/xsd/demo-2.xml
<?xml version="1.0" encoding="UTF-8"?>
<root 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="demo-2.xsd">
  <!-- строки -->
  <str>Abstract string</str>
  <lang>ru-RU</lang>
  <name>abc:xyz</name>
  <ncname>abc-xyz</ncname>
  <!-- числа -->
  <byte>127</byte>
  <positive>45</positive>
  <positive-or-zero>0</positive-or-zero>
  <!-- дата и время -->
  <now>2021-03-04T16:40:23</now>
  <birthday>2009-03-15</birthday>
  <period>P1Y2M3DT12H34M87S</period>
  <!-- другое -->
  <bool>true</bool>
  <hex>45FCAB</hex>
  <url>http://ithub.ru</url>
</root>
