=== whitespace-v/xml/xsd/demo-8.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	
  
  <xs:simpleType name='AgeType'>
    <xs:restriction base='xs:integer'>
      <xs:minInclusive value='18'/>
      <xs:maxExclusive value='65'/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name='LoginType'>
    <xs:restriction base='xs:string'>
      <xs:minLength value='3'/>
      <xs:maxLength value='35'/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name='ColorType'>
    <xs:restriction base='xs:string'>
      <xs:pattern value='([A-Fa-f0-9]{2}){3}'/>
    </xs:restriction>
  </xs:simpleType>
  
  <xs:simpleType name='DayType'>
    <xs:restriction base='xs:string'>
      <xs:enumeration value='Понедельник'/>
      <xs:enumeration value='Вторник'/>
      <xs:enumeration value='Среда'/>
      <xs:enumeration value='Четверг'/>
      <xs:enumeration value='Пятница'/>
    </xs:restriction>
  </xs:simpleType>
  
  <xs:simpleType name='PhoneType'>
    <xs:restriction base='xs:string'>
      <xs:pattern value='\d{3}-?\d{2}-?\d{2}'/>
    </xs:restriction>
  </xs:simpleType>
  
  <xs:simpleType name='PhraseType'>
    <xs:list itemType='xs:string'/>
  </xs:simpleType>
  
  <xs:simpleType name='SizeByNo'>
    <xs:restriction base='xs:integer'>
      <xs:minInclusive value='42'/>
      <xs:maxInclusive value='56'/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name='SizeByStr'>
    <xs:restriction base='xs:string'>
      <xs:enumeration value='XS'/>
      <xs:enumeration value='S'/>
      <xs:enumeration value='M'/>
      <xs:enumeration value='L'/>
      <xs:enumeration value='XL'/>
    </xs:restriction>
  </xs:simpleType>
  
  <xs:simpleType name='SizeType'>
    <xs:union memberTypes='SizeByNo SizeByStr'/>
  </xs:simpleType>
  
	<xs:complexType name='myRootType'>
    <xs:sequence>
      <xs:element name='login' type='LoginType'/>
      <xs:element name='age' type='AgeType'/>
      <xs:element name='color' type='ColorType'/>
      <xs:element name='dayoff' type='DayType'/>
      <xs:element name='phone' type='PhoneType'/>
      <xs:element name='phrase' type='PhraseType'/>
      <xs:element name='size' type='SizeType'/>
    </xs:sequence>
  </xs:complexType>
  
	<xs:element name='root' type='myRootType'/>
	
</xs:schema>

=== whitespace-v/xml/xsd/demo-8.xml
<?xml version="1.0" encoding="UTF-8"?>
<root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
      xsi:noNamespaceSchemaLocation="demo-8.xsd">
  <login>vasya</login>
  <age>64</age>
  <color>FFCFAA</color>
  <dayoff>Среда</dayoff>
  <phone>123-45-78</phone>
  <phrase>I love XML Schema</phrase>
  <size>48</size>
  <size>M</size>
</root>
